
-- seller_gmv_concentration.sql

-- Analysis #3: Seller GMV Concentration + Fulfillment Risk
--
-- Business questions:
-- 1. How concentrated is marketplace GMV across sellers?
-- 2. How much GMV is exposed to sellers with elevated fulfillment risk?
--
-- Key finding from the Pareto analysis:
-- Marketplace GMV is highly concentrated: just 17.6% of sellers
-- generate approximately 80% of total GMV.
--
-- Specifically:
-- 544 of 3,095 sellers are required to reach the 80% GMV threshold.
--
-- This means a relatively small seller cohort is commercially critical,
-- so fulfillment problems among these sellers matter more to the marketplace.

WITH seller_gmv AS (

    -- Calculate marketplace GMV at seller grain.
    -- GMV is defined here as product sales value excluding freight.

    SELECT
        seller_key,
        SUM(item_price) AS gmv

    FROM {{ ref('fact_order_items') }}

    GROUP BY seller_key

),

pareto_base AS (

    -- Rank sellers from highest to lowest GMV.
    -- Then calculate cumulative GMV so we can identify
    -- how many sellers are needed to generate 80% of marketplace GMV.

    SELECT
        seller_key,

        ROW_NUMBER() OVER (
            ORDER BY gmv DESC
        ) AS seller_rank,

        gmv,

        SUM(gmv) OVER (
            ORDER BY gmv DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_gmv,

        SUM(gmv) OVER () AS total_gmv,

        SUM(gmv) OVER (
            ORDER BY gmv DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) * 100.0
        / SUM(gmv) OVER () AS cumulative_percent

    FROM seller_gmv

),

initial_flag AS (

    -- Find the first seller that pushes cumulative GMV
    -- from below 80% to at least 80%.

    SELECT
        *,

        CASE
            WHEN COALESCE(
                    LAG(cumulative_percent) OVER (
                        ORDER BY seller_rank
                    ),
                    0
                 ) < 80.0
                AND cumulative_percent >= 80.0
            THEN 1
            ELSE 0
        END AS is_80_pct_mark

    FROM pareto_base

),

pareto_flag AS (

    -- Propagate the Pareto flag backwards so that every seller
    -- required to reach the 80% threshold is included.

    SELECT
        *,

        MAX(is_80_pct_mark) OVER (
            ORDER BY seller_rank
            ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
        ) AS is_pareto

    FROM initial_flag

),

pareto_sellers AS (

    -- Commercially important seller cohort:
    -- 544 sellers, representing 17.6% of all sellers,
    -- generate approximately 80% of marketplace GMV.

    SELECT
        seller_key,
        seller_rank,
        gmv,
        cumulative_gmv,
        total_gmv,
        cumulative_percent

    FROM pareto_flag

    WHERE is_pareto = 1

),

risky_pareto AS (

    -- Connect commercial importance to fulfillment risk.
    --
    -- Only sellers classified as:
    --   1. High Volume Fulfillment Risk
    --   2. Priority Intervention
    -- are included here.
    --
    -- These sellers combine meaningful commercial exposure
    -- with elevated severe-delay performance.
    --
    -- Note:
    -- The fulfillment-risk model only includes sellers with
    -- at least 100 delivered orders, so this is a conservative
    -- comparison focused on sellers with enough volume for
    -- more reliable rate-based evaluation.

    SELECT
        p.seller_key,
        p.seller_rank,
        p.gmv,
        p.cumulative_percent,

        f.seller_segment,
        f.delivered_orders,
        f.severe_delay_orders,
        f.severe_delay_rate,
        f.poor_review_rate

    FROM pareto_sellers p

    JOIN {{ ref('seller_fulfillment_risk') }} f
        ON p.seller_key = f.seller_key

    WHERE f.seller_segment IN (
        'High Volume Fulfillment Risk',
        'Priority Intervention'
    )

)

SELECT
    -- Number of commercially important sellers
    -- that also show elevated fulfillment risk.

    COUNT(*) AS risky_pareto_sellers,


    -- GMV generated by those risky Pareto sellers.

    ROUND(
        SUM(gmv),
        2
    ) AS risky_pareto_gmv,


    -- Measures how much of the entire marketplace GMV
    -- is exposed to commercially important sellers
    -- with elevated fulfillment risk.

    ROUND(
        SUM(gmv) * 100.0
        / (
            SELECT MAX(total_gmv)
            FROM pareto_sellers
        ),
        2
    ) AS share_of_total_marketplace_gmv,


    -- Measures how much of the commercially critical
    -- Pareto cohort's GMV comes from high-risk sellers.

    ROUND(
        SUM(gmv) * 100.0
        / (
            SELECT SUM(gmv)
            FROM pareto_sellers
        ),
        2
    ) AS share_of_pareto_gmv

FROM risky_pareto


